name: bustick
description: A new Flutter application.


publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  url_launcher: ^5.7.10
  smooth_star_rating: ^1.1.1
  image_picker: ^0.6.3+1
  fluttertoast: ^7.1.5
  flutter_svg: ^0.19.0
  dropdown_search: ^0.5.0
  ticket_card: ^0.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/onboard/
    - assets/svg/
    - assets/images/bus/
    - assets/images/icon/

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat.ttf
 
